# Generated by Django 3.1 on 2020-08-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0035_paperwallet_user_verification'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='wallet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_profiles', to='wallet.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profiles', to='wallet.wallet'),
            preserve_default=False,
        ),
    ]
