# Generated by Django 3.1 on 2020-08-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0038_auto_20200826_1340'),
        ('profiles', '0003_auto_20200812_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['created_at'], 'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address_street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address_town',
            field=models.CharField(blank=True, max_length=128, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=15, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='wallet.wallet', verbose_name='Wallet'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_town',
            field=models.CharField(blank=True, max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone_number',
            field=models.CharField(help_text='Format: +41 7X XXX XX XX', max_length=16, verbose_name='Phonenumber'),
        ),
    ]
