# Generated by Django 3.1 on 2021-03-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_auto_20210316_0738"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyprofile",
            old_name="phone_number",
            new_name="telephone_number",
        ),
    ]
