# Generated by Django 3.1 on 2021-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_auto_20210316_0936"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="google_business_account",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
