# Generated by Django 2.2.13 on 2020-07-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_verificationinput"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
    ]
