# Generated by Django 2.2.13 on 2020-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20200708_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='token_id',
            field=models.IntegerField(null=True),
        ),
    ]
