# Generated by Django 2.2.13 on 2020-07-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_currency_token_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationInput',
        ),
    ]
