# Generated by Django 2.2.13 on 2020-07-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_delete_verificationinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='campaign_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='claim_deadline',
            field=models.DateField(null=True),
        ),
    ]
