# Generated by Django 2.2.13 on 2020-07-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0008_auto_20200720_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="starting_capital",
            field=models.IntegerField(default=10),
        ),
    ]
