# Generated by Django 2.2.14 on 2020-08-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_currency_owner_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='token_id',
            field=models.IntegerField(unique=True),
        ),
    ]
