# Generated by Django 2.2.14 on 2020-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0013_auto_20200805_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="token_id",
            field=models.IntegerField(),
        ),
    ]
