# Generated by Django 2.2.14 on 2020-08-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20200805_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='owner_wallet',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currencies', to='wallet.OwnerWallet'),
        ),
    ]
