# Generated by Django 3.1 on 2020-09-10 09:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0017_auto_20200813_1415"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="Payout account name"),
                ),
                (
                    "bank_clearing_number",
                    models.CharField(
                        max_length=32,
                        verbose_name="Payout account bank clearing number",
                    ),
                ),
                (
                    "iban",
                    models.CharField(max_length=16, verbose_name="Payout account IBAN"),
                ),
                (
                    "currency",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "PayoutAccount",
                "verbose_name_plural": "PayoutAccounts",
            },
        ),
    ]
