# Generated by Django 3.1 on 2020-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0018_payoutaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutaccount",
            name="payout_notes",
            field=models.CharField(
                default="payout", max_length=64, verbose_name="Notes for payout"
            ),
            preserve_default=False,
        ),
    ]
