# Generated by Django 3.1 on 2020-09-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0040_auto_20200915_1245"),
        ("currency", "0022_auto_20200914_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="cashout_wallet",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cashout_currencies",
                to="wallet.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="owner_wallet",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="owner_currencies",
                to="wallet.ownerwallet",
            ),
        ),
    ]
