# Generated by Django 3.1 on 2020-09-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0023_auto_20200915_1245"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Währung", "verbose_name_plural": "Währungen"},
        ),
        migrations.AlterModelOptions(
            name="payoutaccount",
            options={
                "verbose_name": "Auszahlungskonto",
                "verbose_name_plural": "Auszahlungskontos",
            },
        ),
        migrations.AlterField(
            model_name="currency",
            name="allow_minting",
            field=models.BooleanField(default=True, verbose_name="Minting zulassen"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="campaign_end",
            field=models.DateField(null=True, verbose_name="Kampagne start"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="claim_deadline",
            field=models.DateField(null=True, verbose_name="Spätestes Einlösungsdatum"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="decimals",
            field=models.IntegerField(default=0, verbose_name="Dezimalstellen"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="max_claims",
            field=models.IntegerField(
                default=5, verbose_name="Maximale Anzahl Einlösungen"
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="starting_capital",
            field=models.IntegerField(default=10, verbose_name="Startbetrag"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="token_id",
            field=models.IntegerField(verbose_name="Token ID"),
        ),
        migrations.AlterField(
            model_name="payoutaccount",
            name="bank_clearing_number",
            field=models.CharField(max_length=32, verbose_name="Clearingnummer"),
        ),
        migrations.AlterField(
            model_name="payoutaccount",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Kontoname"),
        ),
        migrations.AlterField(
            model_name="payoutaccount",
            name="payout_notes",
            field=models.CharField(max_length=64, verbose_name="Auszahlungsmitteilung"),
        ),
    ]
