# Generated by Django 3.1 on 2020-09-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0040_auto_20200915_1245"),
        ("currency", "0024_auto_20200915_1347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="cashout_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cashout_currencies",
                to="wallet.wallet",
            ),
        ),
    ]
