# Generated by Django 3.1 on 2021-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0026_auto_20200918_0626"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Is public"),
        ),
    ]
