# Generated by Django 3.1 on 2021-03-08 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0027_currency_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "permissions": [("can_view_all_currencies", "Can view all currencies")],
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.AddField(
            model_name="currency",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
