# Generated by Django 3.1 on 2021-03-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0030_auto_20210308_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="needs_sms_verification",
            field=models.BooleanField(
                default=True, verbose_name="Mandatory SMS verification"
            ),
        ),
    ]
