# Generated by Django 2.2.13 on 2020-07-16 14:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currency", "0006_auto_20200716_1354"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationEntry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(1, "Open"), (2, "Claimed"), (3, "Requested")],
                        default=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationInput",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("used_for_companies", models.BooleanField(default=False)),
                (
                    "input_type",
                    models.IntegerField(
                        choices=[
                            (1, "Text"),
                            (2, "Boolean"),
                            (3, "Date"),
                            (4, "Number"),
                        ],
                        default=1,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("csv_col", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="currency.Currency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationInputData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.CharField(max_length=128)),
                (
                    "verificaiton_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="verification.VerificationInput",
                    ),
                ),
                (
                    "verification_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="verification.VerificationEntry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
