# Generated by Django 2.2.13 on 2020-07-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationinputdata',
            old_name='verificaiton_input',
            new_name='verification_input',
        ),
    ]
