# Generated by Django 2.2.14 on 2020-07-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20200716_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationinput',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
            preserve_default=False,
        ),
    ]
