# Generated by Django 2.2.13 on 2020-07-21 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20200720_1428'),
        ('verification', '0003_auto_20200720_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('telephone_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyVerification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('uid', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=128, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=128, null=True)),
                ('owner_telephone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
