# Generated by Django 2.2.13 on 2020-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_auto_20200722_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='telephone_number',
            field=models.CharField(max_length=16),
        ),
    ]
