# Generated by Django 3.1 on 2020-08-08 09:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("verification", "0008_auto_20200730_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressPinVerification",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Open"),
                            (2, "Pending"),
                            (3, "Claimed"),
                            (5, "Failes"),
                        ],
                        default=1,
                    ),
                ),
                ("pin", models.CharField(blank=True, max_length=8)),
                (
                    "company_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="address_pin_verifications",
                        to="profiles.companyprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMSPinVerification",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Open"),
                            (2, "Pending"),
                            (3, "Claimed"),
                            (5, "Failes"),
                        ],
                        default=1,
                    ),
                ),
                ("pin", models.CharField(blank=True, max_length=8)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sms_pin_verifications",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="verificationinput",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="verificationinputdata",
            name="verification_entry",
        ),
        migrations.RemoveField(
            model_name="verificationinputdata",
            name="verification_input",
        ),
        migrations.RenameField(
            model_name="userverification",
            old_name="address",
            new_name="address_street",
        ),
        migrations.RenameField(
            model_name="userverification",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="companyverification",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="companyverification",
            name="owner_address",
        ),
        migrations.RemoveField(
            model_name="companyverification",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="companyverification",
            name="owner_telephone_number",
        ),
        migrations.RemoveField(
            model_name="companyverification",
            name="receiving_wallet",
        ),
        migrations.RemoveField(
            model_name="userverification",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="userverification",
            name="receiving_wallet",
        ),
        migrations.RemoveField(
            model_name="userverification",
            name="telephone_number",
        ),
        migrations.AddField(
            model_name="companyverification",
            name="company_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_verifications",
                to="profiles.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="userverification",
            name="address_postal_code",
            field=models.CharField(default="6302", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userverification",
            name="address_town",
            field=models.CharField(default="Wetzikon", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userverification",
            name="last_name",
            field=models.CharField(default="-", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userverification",
            name="user_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_verifications",
                to="profiles.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="companyverification",
            name="state",
            field=models.IntegerField(
                choices=[(1, "Open"), (2, "Pending"), (3, "Claimed"), (5, "Failes")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="companyverification",
            name="uid",
            field=models.CharField(default="-", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userverification",
            name="state",
            field=models.IntegerField(
                choices=[(1, "Open"), (2, "Pending"), (3, "Claimed"), (5, "Failes")],
                default=1,
            ),
        ),
        migrations.DeleteModel(
            name="VerificationEntry",
        ),
        migrations.DeleteModel(
            name="VerificationInput",
        ),
        migrations.DeleteModel(
            name="VerificationInputData",
        ),
    ]
