# Generated by Django 3.1 on 2020-08-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_auto_20200812_1205"),
        ("verification", "0009_auto_20200808_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresspinverification",
            name="company_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="address_pin_verification",
                to="profiles.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="companyverification",
            name="company_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_verification",
                to="profiles.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="smspinverification",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sms_pin_verification",
                to="profiles.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_verification",
                to="profiles.userprofile",
            ),
        ),
    ]
