# Generated by Django 3.1 on 2020-08-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200812_1247'),
        ('verification', '0011_auto_20200812_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresspinverification',
            name='company_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_pin_verification', to='profiles.companyprofile'),
        ),
        migrations.AlterField(
            model_name='smspinverification',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_pin_verification', to='profiles.userprofile'),
        ),
    ]
