# Generated by Django 3.1 on 2020-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0015_auto_20200827_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresspinverification",
            name="external_id",
            field=models.CharField(blank=True, editable=False, max_length=36),
        ),
    ]
