# Generated by Django 3.1 on 2020-09-09 07:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0017_auto_20200901_1445"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceOfOrigin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("place_of_origint", models.CharField(max_length=128)),
                (
                    "user_verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places_of_origin",
                        to="verification.userverification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
