# Generated by Django 3.1 on 2020-09-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200826_1340'),
        ('verification', '0017_auto_20200901_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresspinverification',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Claimed'), (5, 'Failed'), (6, 'Max Claims')], default=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Claimed'), (5, 'Failed'), (6, 'Max Claims')], default=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='smspinverification',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Claimed'), (5, 'Failed'), (6, 'Max Claims')], default=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='smspinverification',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_pin_verifications', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Claimed'), (5, 'Failed'), (6, 'Max Claims')], default=1, verbose_name='State'),
        ),
    ]
