# Generated by Django 3.1 on 2020-09-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0019_auto_20200909_0752"),
        ("verification", "0018_auto_20200910_0929"),
    ]

    operations = []
