# Generated by Django 3.1 on 2020-09-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0020_merge_20200911_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresspinverification',
            name='notes',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='notes',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='smspinverification',
            name='notes',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='userverification',
            name='notes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
