# Generated by Django 3.1 on 2020-09-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0021_auto_20200911_1511'),
        ('verification', '0021_auto_20200914_0800'),
    ]

    operations = [
    ]
