# Generated by Django 3.1 on 2020-09-15 14:50

from django.db import migrations
from apps.verification.models import UserVerification


def update_user_verifications(apps, schema_editor):
    UserVerification.objects.filter(address_street__isnull=True).update(address_street='no_street')
    UserVerification.objects.filter(address_town__isnull=True).update(address_town='no_town')
    UserVerification.objects.filter(address_postal_code__isnull=True).update(address_postal_code='no_postal_code')


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0024_auto_20200915_1347'),
    ]

    operations = [
        migrations.RunPython(update_user_verifications),

    ]
