# Generated by Django 3.1 on 2021-03-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0029_auto_20200916_1507"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyverification",
            options={
                "ordering": ["name"],
                "verbose_name": "Company verification",
                "verbose_name_plural": "Company verifications",
            },
        ),
        migrations.AlterModelOptions(
            name="userverification",
            options={
                "ordering": ["last_name"],
                "verbose_name": "User verification",
                "verbose_name_plural": "User verifications",
            },
        ),
    ]
