# Generated by Django 3.1 on 2021-03-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_auto_20201023_0908"),
        ("verification", "0030_auto_20210308_0751"),
    ]

    operations = [
        migrations.AddField(
            model_name="smspinverification",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_pin_verifications",
                to="profiles.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="smspinverification",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_pin_verifications",
                to="profiles.userprofile",
            ),
        ),
    ]
