apiVersion: v1
kind: Secret
metadata:
  name: __NAMESPACE_NAME__-secret
  namespace: __NAMESPACE_NAME__
type: Opaque
stringData:
  DJANGO_DB_USER: __DJANGO_DB_USER_DEVELOPMENT__
  DJANGO_DB_PASSWORD: __DJANGO_DB_PASSWORD_DEVELOPMENT__
