apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __NAMESPACE_NAME__-pvc
  namespace: __NAMESPACE_NAME__
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
  storageClassName: standard
