apiVersion: v1
kind: Service
metadata:
  name: __NAMESPACE_NAME__-backend-service
  namespace: __NAMESPACE_NAME__
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
  selector:
    app: __NAMESPACE_NAME__-backend
