apiVersion: v1
kind: LimitRange
metadata:
  name: ___NAMESPACE_NAME___-limitrange
  namespace: ___NAMESPACE_NAME___
spec:
  limits:
  - default:
      cpu: '1'
      memory: '1000Mi'
    defaultRequest:
      cpu: '0.001'
      memory: 150Mi
    type: Container
