# Generated by Django 2.2.13 on 2020-06-24 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimableAmount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('walletID', models.TextField(unique=True)),
                ('address', models.TextField()),
                ('pub_key', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('state', models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Done')], default=1)),
                ('from_addr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fromtransaction', to='wallet.Wallet')),
                ('to_addr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='totransaction', to='wallet.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
