# Generated by Django 2.2.13 on 2020-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200625_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentransaction',
            name='signature',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
