# Generated by Django 2.2.13 on 2020-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_tokentransaction_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="walletID",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
