# Generated by Django 2.2.13 on 2020-06-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
        ("wallet", "0005_auto_20200625_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="currency.Currency",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="currency.Currency",
            ),
        ),
    ]
