# Generated by Django 2.2.13 on 2020-06-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20200625_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokentransaction',
            old_name='created_at',
            new_name='created',
        ),
    ]
