# Generated by Django 2.2.13 on 2020-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0010_auto_20200713_0615"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_company_wallet",
            field=models.BooleanField(default=False),
        ),
    ]
