# Generated by Django 2.2.13 on 2020-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_wallet_is_company_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
