# Generated by Django 2.2.13 on 2020-07-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0012_auto_20200716_0942"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="address",
        ),
        migrations.DeleteModel(
            name="VerificationData",
        ),
    ]
