# Generated by Django 2.2.13 on 2020-07-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_auto_20200720_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokentransaction',
            old_name='from_addr',
            new_name='from_wallet',
        ),
        migrations.RenameField(
            model_name='tokentransaction',
            old_name='to_addr',
            new_name='to_wallet',
        ),
    ]
