# Generated by Django 2.2.14 on 2020-07-20 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_auto_20200720_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Done'), (4, 'Failed')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submitted_to_chain_at', models.DateTimeField(blank=True)),
                ('operation_hash', models.CharField(blank=True, max_length=128)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_transactions', to='wallet.Wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_transactions', to='wallet.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.Transaction')),
                ('nonce', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('signature', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
        migrations.DeleteModel(
            name='TokenTransaction',
        ),
    ]
