# Generated by Django 2.2.14 on 2020-07-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_auto_20200717_1246'),
        ('wallet', '0017_auto_20200720_0750'),
    ]

    operations = [
    ]
