# Generated by Django 2.2.14 on 2020-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0018_auto_20200720_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="submitted_to_chain_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
