# Generated by Django 2.2.14 on 2020-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20200720_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatransaction',
            name='nonce',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
