# Generated by Django 2.2.14 on 2020-07-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0020_auto_20200720_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metatransaction",
            name="signature",
            field=models.CharField(max_length=128),
        ),
    ]
