# Generated by Django 2.2.14 on 2020-07-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_auto_20200720_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimableamount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
            preserve_default=False,
        ),
    ]
