# Generated by Django 2.2.13 on 2020-07-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0022_auto_20200720_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="claim_count",
            field=models.IntegerField(default=0),
        ),
    ]
