# Generated by Django 2.2.13 on 2020-07-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_wallet_claim_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='claim_count',
        ),
    ]
