# Generated by Django 2.2.13 on 2020-07-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_auto_20200722_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerWallet',
            fields=[
                ('wallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.Wallet')),
                ('private_key', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wallet.wallet',),
        ),
    ]
