# Generated by Django 2.2.14 on 2020-07-24 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_auto_20200722_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='metatransaction',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='WalletPublicKeyTransferRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('old_public_key', models.CharField(max_length=60)),
                ('new_public_key', models.CharField(max_length=60)),
                ('state', models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Done'), (4, 'Failed')], default=1)),
                ('submitted_to_chain_at', models.DateTimeField(blank=True, null=True)),
                ('operation_hash', models.CharField(blank=True, max_length=128)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_requests', to='wallet.Wallet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
