# Generated by Django 2.2.14 on 2020-08-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0026_ownerwallet"),
        ("wallet", "0026_auto_20200724_1231"),
    ]

    operations = []
