# Generated by Django 2.2.14 on 2020-08-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0029_remove_transaction_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
