# Generated by Django 2.2.14 on 2020-08-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0031_cashoutrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="from_transactions",
                to="wallet.Wallet",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="operation_hash",
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="submitted_to_chain_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(
                blank=True, editable=False, max_length=128, unique=True
            ),
        ),
    ]
