# Generated by Django 2.2.14 on 2020-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_auto_20200806_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpublickeytransferrequest',
            name='notes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
