# Generated by Django 3.1 on 2020-08-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0033_walletpublickeytransferrequest_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperWallet",
            fields=[
                (
                    "wallet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wallet.wallet",
                    ),
                ),
                ("private_key", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wallet.wallet",),
        ),
    ]
