# Generated by Django 3.1 on 2020-08-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_auto_20200730_1357'),
        ('wallet', '0034_paperwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperwallet',
            name='user_verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='verification.userverification'),
        ),
    ]
