# Generated by Django 3.1 on 2020-08-12 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0035_paperwallet_user_verification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashoutrequest",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Cash out request",
                "verbose_name_plural": "Cash out requests",
            },
        ),
        migrations.AlterModelOptions(
            name="metatransaction",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Meta transaction",
                "verbose_name_plural": "Meta transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterField(
            model_name="cashoutrequest",
            name="state",
            field=models.IntegerField(
                choices=[(1, "Open"), (2, "Pending"), (3, "Done"), (4, "Failed")],
                default=1,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="cashoutrequest",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cash_out_requests",
                to="wallet.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AlterField(
            model_name="ownerwallet",
            name="private_key",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Privatekey"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="category",
            field=models.IntegerField(
                choices=[(0, "Consumer"), (1, "Company"), (2, "Owner")],
                default=0,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="public_key",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="Publickey"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Unverified"), (1, "Pending"), (2, "Verified")],
                default=0,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=128,
                unique=True,
                verbose_name="Wallet Id",
            ),
        ),
    ]
