# Generated by Django 3.1 on 2020-08-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0036_auto_20200812_2338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="company",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
