# Generated by Django 3.1 on 2020-08-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0037_auto_20200813_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_transactions', to='wallet.wallet', verbose_name='From Wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, editable=False, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_hash',
            field=models.CharField(blank=True, editable=False, max_length=128, verbose_name='Operation hash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Done'), (4, 'Failed')], default=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submitted_to_chain_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Submitted to chain'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_transactions', to='wallet.wallet', verbose_name='To Wallet'),
        ),
    ]
