# Generated by Django 3.1 on 2020-09-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0038_auto_20200826_1340"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
