# Generated by Django 3.1 on 2020-10-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0042_auto_20201013_0554"),
    ]

    operations = [
        migrations.AddField(
            model_name="metatransaction",
            name="from_public_key",
            field=models.CharField(
                blank=True, editable=False, max_length=60, verbose_name="Publickey"
            ),
        ),
    ]
