# Generated by Django 3.1 on 2020-10-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0043_metatransaction_from_public_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metatransaction",
            unique_together={("nonce", "from_public_key")},
        ),
    ]
