# Generated by Django 3.1 on 2021-03-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0030_auto_20210308_0751"),
        ("wallet", "0044_auto_20201022_1554"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="walletpublickeytransferrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="paperwallet",
            name="user_verification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="verification.userverification",
            ),
        ),
    ]
